### ISSUE TITLE
Changeable BASE_URL

### ISSUE THREAD

**Issue by Nenuial** [datawookie/filebin#2]
First of all, thank you for this package. It perfectly fits a need I have for sharing files rapidly and I will be able to integrate it easily into some neat workflows.

I would, however, be interested in using my own instance of filebin2. Are there any chances you will make the BASE_URL variable changeable?

**Comment by datawookie** [comment]
Hi @Nenuial,

I'm very glad that you find this little package useful. I've implemented a `base_url()` function in the `base-url` branch.

Usage:

```r
base_url("https://testnet.binance.vision/")
```

Will you please test and let me know?

Thanks, Andrew.

**Comment by Nenuial** [comment]
Hi @datawookie,

Thanks for the feedback and the offered solution.

Just tried it and it works fine. Thank you very much!

**Comment by datawookie** [comment]
Great. WIll merge that into `master`.
